# This file is a template for all of the settings used in the game.  The game code will
# load this file along with a user_settings.yaml file.  Any settings not present in
# the user_settings.yaml file will default to the default value specified here.  When
# any setting is saved (via the in-game service menu), the user_settings.yaml file
# will be updated with ALL of the entries here without overwriting existing settings.

Machine (Standard):
  'Balls Per Game':
    options: [1,10]
    increments: 1
    default: 3
  'Tilt Warnings':
    options: [1,10]
    increments: 1
    default: 3
  'Maximum Extra Balls':
    options: [0,10]
    increments: 1
    default: 4
  'Maximum Extra Balls/Ball In Play':
    options: [0,10]
    increments: 1
    default: 0
  'Custom Message':
    options: [true,false]
    default: false
  'Clock Style':
    options: ['AM/PM','24 Hour']
    default: 'AM/PM'
  'Date Style':
    options: ['Euro','US']
    default: 'Euro'
  'Show Date and Time':
    options: ['Yes','No']
    default: 'No'
  'Allow Dim Illumination':
    options: ['Yes','No']
    default: 'No'
  'Tournament Play':
    options: ['Yes','No']
    default: 'No'
  'Tournament Type':
    options: ['Local','Internet']
    default: 'Local'
  'Euro. Score Format':
    options: ['Yes','No']
    default: 'No'
  'General Illumination Power Saver':
    options: [0,60]
    increments: 1
    default: 0
  'Power Saver Level':
    options: [1,8]
    increments: 1
    default: 4
  'No Bonus Flips':
    options: ['Yes','No']
    default: 'No'
  'Game Restart':
    options: [true,false]
    default: true
  'Free Play':
    options: ['Yes','No']
    default: 'Yes'
  'Color Display Pixel Size':
    options: [14,10,8]
    default: 8
  'Color Display X Offset':
    options: [-2500,2500]
    increments: 1
    default: 0
  'Color Display Y Offset':
    options: [-2500,2500]
    increments: 1
    default: 195
Sound:
  'Initial volume':
    options: [0.1,1.0]
    increments: 0.1
    default: 0.1
  'Music volume offset':
    options: [-0.4,0.4]
    increments: 0.1
    default: 0
Display:
  'Left side score justify':
    # This example has no default.  The first option (right) will be used as the default.
    options: [right, left]
Replay:
  'Replay Type':
    options: ['none','auto','fixed','incremental']
    default: 'auto'
  'Replay Percentage':
    options: [5,50]
    increments: 1
    default: 10
  'Replay Award':
    options: ['Audit', 'Extra Ball']
    default: 'Audit'
  'Replay Levels':
    options: [1,2,3,4]
    default: 1
  'Replay Level 1':
    options: [50000,5000000]
    increments: 50000
    default: 100000
  'Replay Level 2':
    options: [100000,5000000]
    increments: 50000
    default: 200000
  'Replay Level 3':
    options: [150000,5000000]
    increments: 50000
    default: 300000
  'Replay Level 4':
    options: [200000,5000000]
    increments: 50000
    default: 400000
  'Replay Boost':
    options: [50000,5000000]
    increments: 50000
    default: 100000
  'Special':
    options: ['Audit', 'Extra Ball','Points']
    default: 'Audit'
Highscore:
  'Grand Champion':
    options: [50000000,500000000]
    increments: 50000000
    default: 350000000
Gameplay (Feature):
  'A2.01 Timed Plunger':
    options: [0,120]
    increments: 5
    default: 0
  'Flipper Plunger':
    options: ['No',Yes']
    default: 'No'
  'Loop Lit Timer':
    options: [0,120]
    increments: 5
    default: 15
  'Ramp Lit Timer':
    options: [0,120]
    increments: 5
    default: 30
  'Ball Saver Timer':
    options: [0,15]
    increments: 1
    default: 5
  'Multiball Saver Timer':
    options: [0,15]
    increments: 1
    default: 5
  'Quick Multiball Saver Timer':
    options: [0,15]
    increments: 1
    default: 5
  'Captive Multiball Start':
    options: [1,25]
    increments: 1
    default: 3
  'Captive Multiball Start Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Dog Fight Timer':
    options: [5,30]
    increments: 5
    default: 30
  'Mode Start Lit':
    options: ['Always','Ball Start','Off']
    default: 'Ball Start'
  'Get The Idol Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Get The Idol Difficulty':
    options: ['Easy','Medium','Hard']
    default: 'Medium'
  'Streets Of Cairo Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Well Of Souls BIP Start':
    options: [2,6]
    increments: 1
    default: 6
  'Well Of Souls Ball Save Timer':
    options: [0,15]
    increments: 1
    default: 5
  'Monkey Brains Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Steal The Stones Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Rope Bridge Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Castle Grunwald Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Tank Chase Timer':
    options: [5,120]
    increments: 5
    default: 30
  'The 3 Challenges Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Raven Bar Level Start':
    options: [1,4]
    increments: 1
    default: 1
  'Raven Bar Lives':
    options: [1,9]
    increments: 1
    default: 5
  'Raven Bar Hits For Medallion':
    options: [1,50]
    increments: 1
    default: 20
  'Raven Bar Hits For Extra Ball':
    options: [1,50]
    increments: 1
    default: 15
  'Raven Bar Animate Scores For Hits':
    options: ['Yes','No']
    default: 'Yes'
  'Mine Cart Tunnel Start':
    options: [1,50]
    increments: 1
    default: 25
  'Mine Cart Tunnel Inc.':
    options: [1,20]
    increments: 1
    default: 10
  'Choose Wisely Level Start':
    options: [1,4]
    increments: 1
    default: 1
  'Choose Wisely Choice Timer':
    options: [5,30]
    increments: 5
    default: 20
  'Jackport Multiplier Timer':
    options: [5,120]
    increments: 5
    default: 30
  'Path Of Adventure Start Level':
    options: [1,4]
    increments: 1
    default: 1
  'Adventure Continue Timer':
    options: [0,120]
    increments: 5
    default: 15
  'Path of Adventure Extra Ball/Pit Lit Difficulty':
    options: ['Easy','Hard']
    default: 'Easy'
  'Lower Playfield Extra Ball Lit Hold':
    options: ['On','Off']
    default: 'On'
  'Super Jets Start':
    options: [10,255]
    increments: 10
    default: 100
  'Hand Of Fate Lit Difficulty':
    options: ['Easy','Hard']
    default: 'Easy'
  'Hand Of Fate Timer':
    options: [0,120]
    increments: 5
    default: 0
  'Hold Idol Locks At Game Over':
    options: ['Yes','No']
    default: 'No'
  'Attract Mode Sounds':
    options: ['Yes','No']
    default: 'No'
  'Attract Mode Music':
    options: ['Yes','No']
    default: 'No'
  'Buy Extra Ball - Buy-In Feature':
    options: ['Yes','No']
    default: 'No'
  'Buy-In Ball Saver Timer':
    options: [0,60]
    increments: 5
    default: 15
  'Gun Trigger During Buy-In':
    options: ['Extra Ball','Cancel','Nothing']
    default: 'Extra Ball'
  'Outlane Ball Save':
    options: ['Yes','No']
    default: 'No'
  'Game Ballsaves':
    options: [1,10]
    increments: 1
    default: 3
  'Multiball Ballsaves':
    options: [1,10]
    increments: 1
    default: 2
  'Coin Door Ball Save':
    options: ['Yes','No']
    default: 'Yes'
  'Moonlight Mins to Midnight':
    options: [5,30]
    increments: 5
    default: 15
Network:
  'IP Address':
    options: [0,255]
    increments: 1
    default: 0
  'Subnet':
    options: [0,255]
    increments: 1
    default: 0
  'Gateway':
    options: [0,255]
    increments: 1
    default: 0
  'Tournament Server':
    options: [0,255]
    increments: 1
    default: 0

